/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_activity_SimpleActivity */

#ifndef _Included_com_example_jni_activity_SimpleActivity
#define _Included_com_example_jni_activity_SimpleActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_jni_activity_SimpleActivity_A
#define com_example_jni_activity_SimpleActivity_A 234L
#ifdef __cplusplus
}
#endif
#endif
