/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_activity_AdvancedActivity */

#ifndef _Included_com_example_jni_activity_AdvancedActivity
#define _Included_com_example_jni_activity_AdvancedActivity
#ifdef __cplusplus

//NDK 工具链中的 log库
#include <android/log.h>

#define TAG "szj"
//...我都不知道要传什么,可以借助 JNI 中的宏来传入
#define LOGD(...)__android_log_print(ANDROID_LOG_DEBUG,TAG,__VA_ARGS__);
#define LOGI(...)__android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__);
#define LOGE(...)__android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__);

extern "C" {
#endif
/*
 * Class:     com_example_jni_activity_AdvancedActivity
 * Method:    nativeBasicTypes
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_example_jni_activity_AdvancedActivity_nativeBasicTypes(JNIEnv *, jobject ,
                                                                jint , jdouble ,
                                                                jboolean , jstring,jobjectArray,
                                                                jintArray) ;


JNIEXPORT void JNICALL
Java_com_example_jni_activity_AdvancedActivity_nativeMethod(JNIEnv *, jobject,jobject );


JNIEXPORT void JNICALL
Java_com_example_jni_activity_AdvancedActivity_nativeMethod2(JNIEnv *env, jobject ,
                                                             jobject );

JNIEXPORT void JNICALL
Java_com_example_jni_activity_AdvancedActivity_nativeAllQuote(JNIEnv *, jobject );


JNIEXPORT void JNICALL
Java_com_example_jni_activity_AdvancedActivity_nativeRepairAllQuote(JNIEnv *, jobject );


#ifdef __cplusplus
}
#endif
#endif
