/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_MainActivity */

//解决循环拷贝问题
#ifndef _Included_com_example_jni_MainActivity //如果没有定义这个宏
#define _Included_com_example_jni_MainActivity//就定义这个宏

#ifdef __cplusplus //如果是 C++环境,就使用 C 的环境
extern "C" {//全部采用 C 的方式,采用 C 是为了不准你函数重载(解决函数名冲突的问题)
#endif
#undef com_example_jni_MainActivity_A

    //自动检测 MainActivity 生成宏
#define com_example_jni_MainActivity_A 234L

    //函数的声明
JNIEXPORT jstring JNICALL Java_com_example_jni_MainActivity_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_jni_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jni_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus//如果是 C++ 什么事情都不干
}
#endif
#endif
